version: '3.7'

services:

  db:
    build:
      context: ./
      dockerfile: Dockerfile
    container_name: db_crud
    tty: true
    volumes:
      - type: bind
        source: ./db_mysql
        target: /var/lib/mysql
    ports:
      - "3306:3306"
    expose:
      - "3306"
    networks: 
      - default

networks: 
  default:
    driver: bridge

    